# Generated by Django 4.2.20 on 2025-06-25 15:04

from django.db import migrations, models
import portfolio.models.social_type


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialtype',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL du logo (généré automatiquement après upload ou URL externe)', null=True),
        ),
        migrations.AlterField(
            model_name='socialtype',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='socialtype',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo du réseau social (formats supportés: PNG, JPG, JPEG, SVG)', null=True, upload_to=portfolio.models.social_type.social_type_logo_upload_path),
        ),
    ]
