# Generated by Django 4.2.20 on 2025-07-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_user_banner_url_user_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brief_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
