# Generated by Django 4.2.20 on 2025-07-08 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models.project
import portfolio.models.service


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_user_brief_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, help_text='Icône du service (formats supportés: PNG, JPG, JPEG, WebP, SVG)', null=True, upload_to=portfolio.models.service.service_icon_upload_path)),
                ('icon_url', models.URLField(blank=True, help_text="URL de l'icône (généré automatiquement après upload ou URL externe)", null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix du service en euros', max_digits=10, null=True)),
                ('duration_hours', models.PositiveIntegerField(blank=True, help_text='Durée estimée en heures', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Service disponible à la commande')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags pour catégoriser le service (ex: ['web', 'design', 'mobile'])")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='portfolio_s_user_id_09849a_idx'), models.Index(fields=['order'], name='portfolio_s_order_1c6e18_idx'), models.Index(fields=['created_at'], name='portfolio_s_created_6010d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Image du projet (formats supportés: PNG, JPG, JPEG, WebP)', null=True, upload_to=portfolio.models.project.project_image_upload_path)),
                ('image_url', models.URLField(blank=True, help_text="URL de l'image (généré automatiquement après upload ou URL externe)", null=True)),
                ('technologies', models.JSONField(blank=True, default=list, help_text='Liste des technologies utilisées dans le projet')),
                ('demo_url', models.URLField(blank=True, help_text='URL de démonstration du projet', null=True)),
                ('github_url', models.URLField(blank=True, help_text='URL du repository GitHub', null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='portfolio_p_user_id_74641c_idx'), models.Index(fields=['order'], name='portfolio_p_order_2e0f4e_idx'), models.Index(fields=['created_at'], name='portfolio_p_created_6dcf92_idx')],
            },
        ),
    ]
