# Generated by Django 4.2.20 on 2025-07-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_education_title_experience_title_service_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='portfolio_p_user_id_74641c_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='portfolio_p_order_2e0f4e_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user'], name='portfolio_p_user_id_fc22b0_idx'),
        ),
    ]
