# Generated by Django 4.2.20 on 2025-07-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='portfolio_s_order_1c6e18_idx',
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
    ]
